import React, { useState, useEffect } from 'react';
import { Variable } from '../types';
import { generateCppAdaptivityCode } from '../services/geminiService';

interface CodeExportModalProps {
    isOpen: boolean;
    onClose: () => void;
    variables: Variable[];
}

const CodeExportModal: React.FC<CodeExportModalProps> = ({ isOpen, onClose, variables }) => {
    const [code, setCode] = useState<string>('// Initializing C++ generator...');
    const [isLoading, setIsLoading] = useState<boolean>(false);
    const [copyState, setCopyState] = useState<'idle' | 'copied'>('idle');

    useEffect(() => {
        if (isOpen) {
            generateCode();
        }
    }, [isOpen]);

    // Re-generate if variables change while open
    useEffect(() => {
        if (isOpen && variables.length > 0) {
            // simple debounce or check if code needs update could be here, 
            // but for now we re-generate to ensure adaptivity to changes.
            generateCode();
        }
    }, [variables]);

    const generateCode = async () => {
        setIsLoading(true);
        try {
            const generated = await generateCppAdaptivityCode(variables);
            setCode(generated);
        } catch (err) {
            setCode("// Failed to generate code. Please try again.");
        } finally {
            setIsLoading(false);
        }
    };

    const handleCopy = () => {
        navigator.clipboard.writeText(code).then(() => {
            setCopyState('copied');
            setTimeout(() => setCopyState('idle'), 2000);
        });
    };
    
    const handleDownload = () => {
        const blob = new Blob([code], { type: 'text/plain' });
        const url = URL.createObjectURL(blob);
        const a = document.createElement('a');
        a.href = url;
        a.download = 'AdaptiveOptimizer.cpp';
        document.body.appendChild(a);
        a.click();
        document.body.removeChild(a);
        URL.revokeObjectURL(url);
    };

    if (!isOpen) return null;

    return (
        <div className="fixed inset-0 z-50 flex items-center justify-center bg-black/90 backdrop-blur-sm p-4 animate-in fade-in duration-200">
            <div className="bg-[#1e1e1e] w-full max-w-5xl h-[85vh] rounded-xl shadow-2xl border border-gray-700 flex flex-col overflow-hidden">
                
                {/* Header */}
                <div className="flex items-center justify-between px-6 py-4 bg-[#252526] border-b border-[#333]">
                    <div className="flex items-center gap-3">
                        <div className="bg-blue-600/20 p-2 rounded-lg">
                             <svg className="w-6 h-6 text-blue-400" fill="none" stroke="currentColor" viewBox="0 0 24 24"><path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M10 20l4-16m4 4l4 4-4 4M6 16l-4-4 4-4" /></svg>
                        </div>
                        <div>
                            <h2 className="text-lg font-bold text-gray-200">Adaptive Logic Engine (C++17)</h2>
                            <p className="text-xs text-gray-500 font-mono">Generated by Gemini 3.0 Pro</p>
                        </div>
                    </div>
                    <button onClick={onClose} className="text-gray-400 hover:text-white transition-colors">
                        <svg className="w-6 h-6" fill="none" stroke="currentColor" viewBox="0 0 24 24"><path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M6 18L18 6M6 6l12 12" /></svg>
                    </button>
                </div>

                {/* Code Area */}
                <div className="flex-grow overflow-auto relative bg-[#1e1e1e] custom-scrollbar group">
                    {isLoading ? (
                        <div className="absolute inset-0 flex flex-col items-center justify-center text-gray-400 gap-4">
                            <div className="w-12 h-12 border-4 border-blue-500/30 border-t-blue-500 rounded-full animate-spin"></div>
                            <div className="font-mono text-sm animate-pulse">Synthesizing logic structures...</div>
                        </div>
                    ) : (
                        <pre className="p-6 text-sm font-mono leading-relaxed text-[#d4d4d4] tab-4">
                            <code>{code}</code>
                        </pre>
                    )}
                </div>

                {/* Footer Actions */}
                <div className="p-4 bg-[#252526] border-t border-[#333] flex justify-between items-center">
                    <div className="text-xs text-gray-500 flex gap-4">
                        <span>Lines: {code.split('\n').length}</span>
                        <span>Encoding: UTF-8</span>
                        <span>Target: Embedded/Linux</span>
                    </div>
                    <div className="flex gap-3">
                        <button 
                            onClick={handleCopy}
                            disabled={isLoading}
                            className="px-4 py-2 bg-[#333] hover:bg-[#444] text-white text-xs font-medium uppercase tracking-wide rounded border border-[#555] transition-colors flex items-center gap-2"
                        >
                            {copyState === 'copied' ? (
                                <>
                                    <svg className="w-4 h-4 text-green-400" fill="none" stroke="currentColor" viewBox="0 0 24 24"><path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M5 13l4 4L19 7" /></svg>
                                    Copied
                                </>
                            ) : (
                                <>
                                    <svg className="w-4 h-4" fill="none" stroke="currentColor" viewBox="0 0 24 24"><path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M8 16H6a2 2 0 01-2-2V6a2 2 0 012-2h8a2 2 0 012 2v2m-6 12h8a2 2 0 002-2v-8a2 2 0 00-2-2h-8a2 2 0 00-2 2v8a2 2 0 002 2z" /></svg>
                                    Copy Code
                                </>
                            )}
                        </button>
                        <button 
                            onClick={handleDownload}
                            disabled={isLoading}
                            className="px-4 py-2 bg-blue-700 hover:bg-blue-600 text-white text-xs font-medium uppercase tracking-wide rounded shadow-lg transition-colors flex items-center gap-2"
                        >
                            <svg className="w-4 h-4" fill="none" stroke="currentColor" viewBox="0 0 24 24"><path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M4 16v1a3 3 0 003 3h10a3 3 0 003-3v-1m-4-4l-4 4m0 0l-4-4m4 4V4" /></svg>
                            Download .cpp
                        </button>
                    </div>
                </div>
            </div>
        </div>
    );
};

export default CodeExportModal;