import React, { useState, useEffect, useMemo } from 'react';
import { AnalysisResult, Variable } from '../types';
import { BarChart, Bar, XAxis, YAxis, Tooltip, ResponsiveContainer, Cell, ReferenceLine } from 'recharts';

interface ResultsDisplayProps {
    result: AnalysisResult | null;
    insights: string;
    isLoading: boolean;
    variables: Variable[]; // Needed for context in leverage calculation
    mode?: 'general' | 'financial' | 'health' | 'medical';
    onExportCpp?: () => void;
}

const ResultsDisplay: React.FC<ResultsDisplayProps> = ({ result, insights, isLoading, variables, mode = 'general', onExportCpp }) => {
    // Store temporary adjustments to probabilities for the "What If" simulator
    const [simulatedValues, setSimulatedValues] = useState<Record<string, number>>({});
    const [copyStatus, setCopyStatus] = useState<'idle' | 'copied'>('idle');

    const getColors = () => {
        if (mode === 'financial') return { main: 'emerald', hex: '#10B981' };
        if (mode === 'health') return { main: 'rose', hex: '#F43F5E' };
        if (mode === 'medical') return { main: 'indigo', hex: '#6366F1' };
        return { main: 'cyan', hex: '#22D3EE' };
    };

    const theme = getColors();

    useEffect(() => {
        if (result) {
            const initial: Record<string, number> = {};
            result.bestCombination.forEach(item => {
                initial[item.variableName] = item.baseProbability;
            });
            setSimulatedValues(initial);
        }
    }, [result]);

    const handleExportJson = () => {
        if (!result) return;

        const exportData = {
            appName: "Probabilistic Outcome Analyzer",
            mode: mode,
            date: new Date().toISOString(),
            targetOutcome: result.outcomeName,
            baseProbability: `${(result.highestProbability * 100).toFixed(2)}%`,
            optimalPath: result.bestCombination.map(c => ({
                variable: c.variableName,
                choice: c.stateName,
                probability: c.baseProbability
            })),
            aiInsights: insights
        };

        const jsonString = JSON.stringify(exportData, null, 2);
        const blob = new Blob([jsonString], { type: 'application/json' });
        const href = URL.createObjectURL(blob);
        const link = document.createElement('a');
        link.href = href;
        link.download = `POA_${mode}_Analysis_${new Date().toISOString().slice(0,10)}.json`;
        document.body.appendChild(link);
        link.click();
        document.body.removeChild(link);
        URL.revokeObjectURL(href);
    };

    const handleExportNotebookLM = () => {
        if (!result) return;

        let title = "STRATEGIC OUTCOME REPORT";
        if (mode === 'financial') title = "FINANCIAL ADVISORY REPORT";
        if (mode === 'health') title = "ATHLETIC PERFORMANCE REPORT";
        if (mode === 'medical') title = "CLINICAL ASSESSMENT REPORT";
        
        const textReport = `
${title}
=====================================
Date: ${new Date().toLocaleDateString()}
Target: ${result.outcomeName}
Mode: ${mode.toUpperCase()}

EXECUTIVE SUMMARY
-----------------
${insights.replace(/[*#]/g, '')}

OPTIMAL ${mode === 'financial' ? 'PORTFOLIO/PATH' : mode === 'health' ? 'TRAINING PROTOCOL' : mode === 'medical' ? 'CLINICAL PATH' : 'STRATEGY PATH'}
---------------------
Achieves ${(result.highestProbability * 100).toFixed(2)}% Probability of ${result.outcomeName}.

${result.bestCombination.map(c => `• ${c.variableName}: Choose "${c.stateName}" (Base Prob: ${c.baseProbability}%)`).join('\n')}

DETAILED MODEL DEFINITION
-------------------------
${variables.map(v => 
    `Variable: ${v.name}
    States:
    ${v.states.map(s => `  - ${s.name} (Outcomes: ${s.outcomes.map(o => `${o.name}=${o.probability}%`).join(', ')})`).join('\n')}`
).join('\n\n')}

-------------------------------------
Generated by Probabilistic Outcome Analyzer
`;

        const blob = new Blob([textReport], { type: 'text/plain' });
        const href = URL.createObjectURL(blob);
        const link = document.createElement('a');
        link.href = href;
        link.download = `${mode}_Report.txt`;
        document.body.appendChild(link);
        link.click();
        document.body.removeChild(link);
        URL.revokeObjectURL(href);
    };

    const handleCopySocial = () => {
        if (!result) return;
        
        let headerIcon = '🚀';
        let footerTags = '#Strategy #AI';
        let contextText = 'Optimized Strategy:';
        
        if (mode === 'financial') {
            headerIcon = '📈';
            footerTags = '#Finance #Investing #WealthManagement';
            contextText = 'Financial Outlook:';
        } else if (mode === 'health') {
            headerIcon = '💪';
            footerTags = '#Fitness #BioHacking #SportsScience';
            contextText = 'Performance Protocol:';
        } else if (mode === 'medical') {
            headerIcon = '⚕️';
            footerTags = '#MedicalResearch #Clinical #HealthTech';
            contextText = 'Clinical Assessment:';
        }
        
        const socialText = `${headerIcon} ${contextText} "${result.outcomeName}"

✨ Winning Path:
${result.bestCombination.map(c => `👉 ${c.variableName}: ${c.stateName}`).join('\n')}

📊 ${mode === 'health' ? 'Performance Probability' : mode === 'medical' ? 'Prognosis Confidence' : 'Confidence Score'}: ${(result.highestProbability * 100).toFixed(2)}%

Analyzed via Probabilistic Outcome Analyzer ${footerTags}`;

        navigator.clipboard.writeText(socialText).then(() => {
            setCopyStatus('copied');
            setTimeout(() => setCopyStatus('idle'), 2000);
        });
    };

    // Recalculate total probability based on slider values
    const simulatedProbability = useMemo(() => {
        if (!result) return 0;
        let prob = 1;
        result.bestCombination.forEach(item => {
            const val = simulatedValues[item.variableName] ?? item.baseProbability;
            prob *= (val / 100);
        });
        return prob;
    }, [result, simulatedValues]);

    const calculateLeverage = (baseProb: number) => {
        if (baseProb === 0) return 999;
        return (100 - baseProb);
    };

    const handleSliderChange = (variableName: string, newValue: number) => {
        setSimulatedValues(prev => ({
            ...prev,
            [variableName]: newValue
        }));
    };

    const renderMarkdown = (text: string) => {
        const headingColor = `text-${theme.main}-400`;
        const subHeadingColor = `text-${theme.main}-300`;

        const lines = text.split('\n');
        return lines.map((line, index) => {
            if (line.startsWith('####')) return <h4 key={index} className={`text-lg font-semibold mt-4 mb-1 ${subHeadingColor}`}>{line.replace('####', '').trim()}</h4>;
            if (line.startsWith('###')) return <h3 key={index} className={`text-xl font-bold mt-4 mb-2 ${headingColor}`}>{line.replace('###', '').trim()}</h3>;
            if (line.startsWith('##')) return <h2 key={index} className={`text-2xl font-bold mt-6 mb-3 ${headingColor}`}>{line.replace('##', '').trim()}</h2>;
            if (line.startsWith('#')) return <h1 key={index} className={`text-3xl font-bold mt-8 mb-4 ${headingColor}`}>{line.replace('#', '').trim()}</h1>;
            if (line.startsWith('- **')) {
                 const boldText = line.match(/\*\*(.*?)\*\*/)?.[1] || '';
                 const restOfText = line.replace(`- **${boldText}**`, '');
                 return <p key={index} className="mb-2"><strong className="font-semibold text-white">{boldText}</strong>{restOfText}</p>;
            }
            if (line.startsWith('- ')) return <li key={index} className="ml-5 list-disc">{line.substring(2)}</li>;
            return <p key={index} className="mb-2 text-gray-300">{line}</p>;
        });
    };

    if (isLoading) {
        return (
            <div className="flex flex-col items-center justify-center h-full text-center">
                <div className={`animate-spin rounded-full h-16 w-16 border-t-2 border-b-2 border-${theme.main}-500 mb-4`}></div>
                <p className="text-lg font-semibold text-gray-300">Running probabilistic model...</p>
                <p className="text-sm text-gray-400">
                    {mode === 'financial' ? 'Consulting financial algorithms...' 
                     : mode === 'health' ? 'Analyzing bio-markers and routines...' 
                     : mode === 'medical' ? 'Evaluating clinical factors and literature...'
                     : 'Querying Gemini for strategic insights...'}
                </p>
            </div>
        );
    }
    
    if (!result) {
        return (
            <div className="flex items-center justify-center h-full text-center text-gray-400">
                <p>Your analysis results and AI insights will appear here.</p>
            </div>
        );
    }

    const baseProbPercent = result.highestProbability * 100;
    const simProbPercent = simulatedProbability * 100;
    const probDelta = simProbPercent - baseProbPercent;

    const leverageSorted = [...result.bestCombination].sort((a, b) => {
        return calculateLeverage(b.baseProbability) - calculateLeverage(a.baseProbability);
    }).reverse();

    const chartData = [
        { name: 'Current', value: baseProbPercent, type: 'Current' },
        { name: 'Simulated', value: simProbPercent, type: 'Simulated' }
    ];

    return (
        <div className="space-y-8 animate-fade-in">
            {/* Header Actions */}
            <div className="flex flex-col sm:flex-row justify-between items-start sm:items-center border-b border-gray-700 pb-4 gap-4">
                <h3 className="text-xl font-bold text-white">
                    {mode === 'financial' ? 'Projected Confidence:' : mode === 'health' ? 'Performance Probability:' : mode === 'medical' ? 'Prognosis Confidence:' : 'Optimal Path:'} <span className={`text-${theme.main}-400`}>{(result.highestProbability * 100).toFixed(2)}%</span>
                </h3>
                
                <div className="flex flex-wrap gap-2">
                    <button
                        onClick={handleCopySocial}
                        className="flex items-center gap-2 text-xs font-medium uppercase tracking-wider bg-blue-900/30 hover:bg-blue-800/50 text-blue-300 hover:text-blue-200 py-2 px-3 rounded-md border border-blue-800/50 transition-all"
                    >
                         {copyStatus === 'copied' ? (
                            <span className="text-green-400 flex items-center gap-1">Copied!</span>
                         ) : (
                             <>Copy Summary</>
                         )}
                    </button>

                    <button
                        onClick={handleExportNotebookLM}
                        className="flex items-center gap-2 text-xs font-medium uppercase tracking-wider bg-purple-900/30 hover:bg-purple-800/50 text-purple-300 hover:text-purple-200 py-2 px-3 rounded-md border border-purple-800/50 transition-all"
                    >
                        NotebookLM Report
                    </button>

                    <button
                        onClick={onExportCpp}
                        className="flex items-center gap-2 text-xs font-medium uppercase tracking-wider bg-slate-700/50 hover:bg-slate-600 text-slate-300 hover:text-white py-2 px-3 rounded-md border border-slate-600 transition-all"
                    >
                        Export Logic Engine
                    </button>
                    
                    <button
                        onClick={handleExportJson}
                        className={`flex items-center gap-2 text-xs font-medium uppercase tracking-wider py-2 px-3 rounded-md transition-all shadow-sm bg-gray-700 hover:bg-gray-600 text-${theme.main}-400 border border-${theme.main}-900`}
                    >
                        JSON
                    </button>
                </div>
            </div>

            {/* Impact Simulator Section */}
            <div className="grid grid-cols-1 lg:grid-cols-2 gap-8">
                <div className="bg-gray-700/30 p-4 rounded-lg border border-gray-600/50">
                    <div className="flex items-center justify-between mb-4">
                        <h4 className="text-md font-bold text-gray-200 flex items-center gap-2">
                            Impact Simulator
                        </h4>
                        <button 
                            onClick={() => setSimulatedValues(Object.fromEntries(result.bestCombination.map(i => [i.variableName, i.baseProbability])))}
                            className="text-xs text-gray-400 hover:text-white underline"
                        >
                            Reset
                        </button>
                    </div>
                    <p className="text-xs text-gray-400 mb-4">Adjust individual probabilities to see how improving a specific area impacts the total outcome.</p>
                    
                    <div className="space-y-4 max-h-80 overflow-y-auto custom-scrollbar pr-2">
                        {result.bestCombination.map((item, idx) => (
                            <div key={idx} className="bg-gray-800/50 p-3 rounded-md">
                                <div className="flex justify-between text-sm mb-1">
                                    <span className="text-gray-300 font-medium truncate w-1/2" title={item.variableName}>{item.variableName}</span>
                                    <span className={`text-${theme.main}-300 font-mono`}>{simulatedValues[item.variableName] ?? item.baseProbability}%</span>
                                </div>
                                <input 
                                    type="range" 
                                    min="0" 
                                    max="100" 
                                    value={simulatedValues[item.variableName] ?? item.baseProbability}
                                    onChange={(e) => handleSliderChange(item.variableName, parseInt(e.target.value))}
                                    className={`w-full h-2 bg-gray-600 rounded-lg appearance-none cursor-pointer accent-${theme.main}-500`}
                                />
                                <div className="flex justify-between text-[10px] text-gray-500 mt-1">
                                    <span>Selected: {item.stateName}</span>
                                    <span>Base: {item.baseProbability}%</span>
                                </div>
                            </div>
                        ))}
                    </div>
                </div>

                <div className="flex flex-col">
                    <h4 className="text-md font-bold text-gray-200 mb-2">Projected Outcome</h4>
                    <div className="flex-grow bg-gray-700/30 p-4 rounded-lg border border-gray-600/50 flex flex-col justify-center">
                        <div className="h-48 w-full mb-4">
                            <ResponsiveContainer width="100%" height="100%">
                                <BarChart data={chartData} layout="vertical" margin={{ top: 5, right: 30, left: 40, bottom: 5 }}>
                                    <XAxis type="number" domain={[0, 100]} hide />
                                    <YAxis type="category" dataKey="name" tick={{ fill: '#9CA3AF', fontSize: 12 }} width={60} />
                                    <Tooltip
                                        cursor={{fill: 'transparent'}}
                                        contentStyle={{ backgroundColor: '#1F2937', border: '1px solid #4B5563', color: '#fff' }}
                                        formatter={(value: number) => [`${value.toFixed(2)}%`, 'Probability']}
                                    />
                                    <ReferenceLine x={baseProbPercent} stroke="#6B7280" strokeDasharray="3 3" />
                                    <Bar dataKey="value" radius={[0, 4, 4, 0]} barSize={30}>
                                        {chartData.map((entry, index) => (
                                            <Cell key={`cell-${index}`} fill={entry.type === 'Current' ? '#4B5563' : (probDelta >= 0 ? theme.hex : '#EF4444')} />
                                        ))}
                                    </Bar>
                                </BarChart>
                            </ResponsiveContainer>
                        </div>
                        
                        <div className="text-center">
                            <p className="text-sm text-gray-400">Simulated Total Probability</p>
                            <div className={`text-4xl font-bold ${probDelta > 0 ? `text-${theme.main}-400` : probDelta < 0 ? 'text-red-400' : 'text-white'}`}>
                                {simProbPercent.toFixed(2)}%
                            </div>
                        </div>
                    </div>
                </div>
            </div>

            {/* Leverage Leaderboard */}
            <div className="bg-gray-800/80 rounded-lg border border-gray-700 p-6">
                <h4 className="text-lg font-bold text-white mb-4 flex items-center gap-2">
                    {mode === 'financial' ? 'Risk Exposure Analysis' : mode === 'health' ? 'Protocol Bottlenecks' : mode === 'medical' ? 'Clinical Contraindications' : 'Leverage Analysis'}
                </h4>
                <p className="text-sm text-gray-400 mb-4">
                    {mode === 'financial' 
                        ? 'Identifying high-risk factors. Variables at the top have the lowest confidence and may require hedging.'
                        : mode === 'health'
                        ? 'Identifying the habits dragging down performance. Focus on improving the top variables.'
                        : mode === 'medical'
                        ? 'Identifying factors most reducing the prognosis probability. Addressing these may improve clinical outcomes.'
                        : 'Identifying the "Weakest Links". Variables at the top offer the highest ROI for improvement efforts.'}
                </p>
                
                <div className="overflow-x-auto">
                    <table className="w-full text-left text-sm text-gray-300">
                        <thead className="bg-gray-700/50 text-xs uppercase text-gray-400">
                            <tr>
                                <th className="px-4 py-3 rounded-tl-lg">Variable</th>
                                <th className="px-4 py-3">Selected State</th>
                                <th className="px-4 py-3">Current Prob.</th>
                                <th className="px-4 py-3 rounded-tr-lg">Improvement Potential</th>
                            </tr>
                        </thead>
                        <tbody className="divide-y divide-gray-700">
                            {leverageSorted.map((item, idx) => {
                                const gap = 100 - item.baseProbability;
                                return (
                                    <tr key={idx} className="hover:bg-gray-700/30 transition">
                                        <td className="px-4 py-3 font-medium text-white">{item.variableName}</td>
                                        <td className="px-4 py-3 text-gray-400">{item.stateName}</td>
                                        <td className="px-4 py-3 font-mono">{item.baseProbability}%</td>
                                        <td className="px-4 py-3">
                                            <div className="flex items-center gap-2">
                                                <div className="flex-grow bg-gray-600 h-2 rounded-full max-w-[100px]">
                                                    <div 
                                                        className="h-2 rounded-full bg-gradient-to-r from-yellow-500 to-red-500" 
                                                        style={{ width: `${gap}%` }}
                                                    ></div>
                                                </div>
                                                <span className="text-xs text-yellow-500">+{gap}%</span>
                                            </div>
                                        </td>
                                    </tr>
                                );
                            })}
                        </tbody>
                    </table>
                </div>
            </div>

            {/* AI Insights Section */}
            {insights && (
                <div className="mt-8">
                    <h3 className="text-xl font-bold text-white mb-3 flex items-center border-t border-gray-700 pt-6">
                         <svg className={`w-6 h-6 mr-2 text-${theme.main}-400`} xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" strokeWidth={1.5} stroke="currentColor">
                           <path strokeLinecap="round" strokeLinejoin="round" d="M9.813 15.904 9 18.75l-.813-2.846a4.5 4.5 0 0 0-3.09-3.09L2.25 12l2.846-.813a4.5 4.5 0 0 0 3.09-3.09L9 5.25l.813 2.846a4.5 4.5 0 0 0 3.09 3.09L15.75 12l-2.846.813a4.5 4.5 0 0 0-3.09 3.09ZM18.259 8.715 18 9.75l-.259-1.035a3.375 3.375 0 0 0-2.455-2.456L14.25 6l1.036-.259a3.375 3.375 0 0 0 2.455-2.456L18 2.25l.259 1.035a3.375 3.375 0 0 0 2.456 2.456L21.75 6l-1.035.259a3.375 3.375 0 0 0-2.456 2.456Z" />
                        </svg>
                        Gemini {mode === 'financial' ? 'Advisory' : mode === 'health' ? 'Performance Coach' : mode === 'medical' ? 'Clinical Assessment' : 'Strategic Insights'}
                    </h3>
                    <div className="prose prose-invert bg-gray-700/50 p-6 rounded-lg text-gray-300 shadow-inner border border-gray-600/50">
                        {renderMarkdown(insights)}
                    </div>
                </div>
            )}
        </div>
    );
};

export default ResultsDisplay;